language: node_js
node_js:
 - "6.9.2"
script: 
 - "npm test"
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- mocha --compilers ts:ts-node/register tests/**/*.test.ts -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js